/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConditionDatetimePicker: typeof import('./src/components/query-condition/ConditionDatetimePicker.vue')['default']
    ConditionInput: typeof import('./src/components/query-condition/ConditionInput.vue')['default']
    ConditionSelect: typeof import('./src/components/query-condition/ConditionSelect.vue')['default']
    LinearLoading: typeof import('./src/components/linear-loading/LinearLoading.vue')['default']
    MonacoEditor: typeof import('./src/components/monaco-editor/MonacoEditor.vue')['default']
    PieChart: typeof import('./src/components/echarts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleTextarea: typeof import('./src/components/simple-textarea/SimpleTextarea.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/SvgIcon.vue')['default']
  }
}
